name: Deploy Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  REPOSITORY: frontend-repo
  SERVICE_NAME: incident-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg VITE_API_URL="${{ secrets.VITE_API_URL }}" \
            -t asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/incident-frontend:${{ github.sha }} \
            .

      - name: Push Docker Image
        run: |
          docker push \
            asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/incident-frontend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE_NAME} \
            --image asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/incident-frontend:${{ github.sha }} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated